### ISSUE TITLE
Sort Array Step 1 

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/functionschallenge#11]
I made a mistake in my Step 1 and needed to run it again to successfully store all 1000 values in the array.  Although I get a success message from the Challenge Site on Step 1, the Monitor tab in my Functions console does not show execution.  The execution log from the Challenge Site is attached, note the lack of an HTTP Status Code.

[2cdc080d-20f6-45df-8a9a-e9cd06a16456.zip](https://github.com/Azure/functionschallenge/files/617989/2cdc080d-20f6-45df-8a9a-e9cd06a16456.zip)

**Comment by fashaikh** [comment]
The monitor tab may take some time to get updated. Does it show up now/after refresh ?
Could you also check this link https://smfunctionschallenge.scm.azurewebsites.net/azurejobs/#/functions  to see if your function execution is listed ?
If it shows up now and was missing earlier then we'll need to track the issue here: https://github.com/projectkudu/azurefunctionsportal/issues 

If it isn't listed in either place, then I'll need to investigate if this is a functioncchallenge issue, or a functions sdk issue where the logging on your function just didn't happen.
