### ISSUE TITLE
Support Office365/Azure AD logins

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/functionschallenge#12]
I had to create a new trial account to do the challenges because you don't support Azure AD logins.

**Comment by fashaikh** [comment]
We currently use azure [AD B2C ](https://azure.microsoft.com/en-us/services/active-directory-b2c/)which currently supports facebook google linkedin microsoft and amazon social auth. We haven't configured linkedin and amazon for now since most people prefer one of the other three major providers. We'll evaluate soon based on the demand and B2C support updates. Alternately we can implement an Azure AD provider like [TryAppService ](https://github.com/projectkudu/TryAppService/blob/master/SimpleWAWS/Authentication/AADProvider.cs)does
